export const dataUsuarios = [
  {
    "id": 1,
    "nombre": "Carlos",
    "apellido": "Gomez",
    "dni": "12345678A",
    "edad": 30,
    "direccion": "Calle Falsa 123",
    "telefono": "612345678",
    "grupo Sanguineo": "O+",
    "diagnostico": "Saludable"
  },
  {
    "id": 2,
    "nombre": "Ana",
    "apellido": "Martinez",
    "dni": "23456789B",
    "edad": 25,
    "direccion": "Avenida Siempre Viva 456",
    "telefono": "623456789",
    "grupo Sanguineo": "A+",
    "diagnostico": "Saludable"
  },
  {
    "id": 3,
    "nombre": "Luis",
    "apellido": "Hernandez",
    "dni": "34567890C",
    "edad": 40,
    "direccion": "Calle Luna 789",
    "telefono": "634567890",
    "grupo Sanguineo": "B-",
    "diagnostico": "Diabetes"
  },
  {
    "id": 4,
    "nombre": "Marta",
    "apellido": "Lopez",
    "dni": "45678901D",
    "edad": 22,
    "direccion": "Calle Sol 159",
    "telefono": "645678901",
    "grupo Sanguineo": "AB+",
    "diagnostico": "Saludable"
  },
  {
    "id": 5,
    "nombre": "Pedro",
    "apellido": "Sanchez",
    "dni": "56789012E",
    "edad": 35,
    "direccion": "Calle Nubes 321",
    "telefono": "656789012",
    "grupo Sanguineo": "O-",
    "diagnostico": "Hipertensión"
  },
  {
    "id": 6,
    "nombre": "Lucia",
    "apellido": "Fernandez",
    "dni": "67890123F",
    "edad": 28,
    "direccion": "Calle Mar 654",
    "telefono": "667890123",
    "grupo Sanguineo": "A-",
    "diagnostico": "Saludable"
  },
  {
    "id": 7,
    "nombre": "Javier",
    "apellido": "García",
    "dni": "78901234G",
    "edad": 32,
    "direccion": "Calle Río 987",
    "telefono": "678901234",
    "grupo Sanguineo": "AB-",
    "diagnostico": "Asma"
  },
  {
    "id": 8,
    "nombre": "Elena",
    "apellido": "Pérez",
    "dni": "89012345H",
    "edad": 27,
    "direccion": "Calle Bosque 321",
    "telefono": "689012345",
    "grupo Sanguineo": "O+",
    "diagnostico": "Saludable"
  },
  {
    "id": 9,
    "nombre": "Andrés",
    "apellido": "Ramirez",
    "dni": "90123456I",
    "edad": 45,
    "direccion": "Calle Estrella 543",
    "telefono": "690123456",
    "grupo Sanguineo": "B+",
    "diagnostico": "Cáncer"
  },
  {
    "id": 10,
    "nombre": "Sara",
    "apellido": "Cruz",
    "dni": "01234567J",
    "edad": 31,
    "direccion": "Calle Playa 876",
    "telefono": "601234567",
    "grupo Sanguineo": "A+",
    "diagnostico": "Saludable"
  },
  {
    "id": 11,
    "nombre": "Raúl",
    "apellido": "Diaz",
    "dni": "12345678K",
    "edad": 29,
    "direccion": "Calle Tierra 210",
    "telefono": "612345678",
    "grupo Sanguineo": "O-",
    "diagnostico": "Colesterol alto"
  },
  {
    "id": 12,
    "nombre": "Nuria",
    "apellido": "Morales",
    "dni": "23456789L",
    "edad": 24,
    "direccion": "Avenida Mar 345",
    "telefono": "623456789",
    "grupo Sanguineo": "AB+",
    "diagnostico": "Saludable"
  },
  {
    "id": 13,
    "nombre": "Miguel",
    "apellido": "Torres",
    "dni": "34567890M",
    "edad": 38,
    "direccion": "Calle Valle 678",
    "telefono": "634567890",
    "grupo Sanguineo": "A-",
    "diagnostico": "Hipertensión"
  },
  {
    "id": 14,
    "nombre": "Laura",
    "apellido": "Rojas",
    "dni": "45678901N",
    "edad": 30,
    "direccion": "Calle Oceano 432",
    "telefono": "645678901",
    "grupo Sanguineo": "B+",
    "diagnostico": "Saludable"
  },
  {
    "id": 15,
    "nombre": "Diego",
    "apellido": "Molina",
    "dni": "56789012O",
    "edad": 26,
    "direccion": "Calle Lago 876",
    "telefono": "656789012",
    "grupo Sanguineo": "O+",
    "diagnostico": "Saludable"
  },
  {
    "id": 16,
    "nombre": "Patricia",
    "apellido": "Vega",
    "dni": "67890123P",
    "edad": 33,
    "direccion": "Calle Horizonte 234",
    "telefono": "667890123",
    "grupo Sanguineo": "AB-",
    "diagnostico": "Asma"
  },
  {
    "id": 17,
    "nombre": "Victor",
    "apellido": "Castro",
    "dni": "78901234Q",
    "edad": 42,
    "direccion": "Calle Sur 654",
    "telefono": "678901234",
    "grupo Sanguineo": "A+",
    "diagnostico": "Saludable"
  },
  {
    "id": 18,
    "nombre": "Cristina",
    "apellido": "Salinas",
    "dni": "89012345R",
    "edad": 21,
    "direccion": "Calle Norte 321",
    "telefono": "689012345",
    "grupo Sanguineo": "O-",
    "diagnostico": "Colesterol alto"
  },
  {
    "id": 19,
    "nombre": "Raquel",
    "apellido": "Aguilar",
    "dni": "90123456S",
    "edad": 34,
    "direccion": "Calle Cordillera 789",
    "telefono": "690123456",
    "grupo Sanguineo": "AB+",
    "diagnostico": "Cáncer"
  },
  {
    "id": 20,
    "nombre": "Santiago",
    "apellido": "Palacios",
    "dni": "01234567T",
    "edad": 39,
    "direccion": "Calle Mariposa 987",
    "telefono": "601234567",
    "grupo Sanguineo": "AB+",
    "diagnostico": "Cáncer"
  },
  {
    "id": 21,
    "nombre": "Claudia",
    "apellido": "Bermudez",
    "dni": "12345678U",
    "edad": 29,
    "direccion": "Calle Colina 654",
    "telefono": "612345678",
    "grupo Sanguineo": "A-",
    "diagnostico": "Saludable"
  },
  {
    "id": 22,
    "nombre": "Fernando",
    "apellido": "Pinto",
    "dni": "23456789V",
    "edad": 36,
    "direccion": "Avenida Azul 321",
    "telefono": "623456789",
    "grupo Sanguineo": "O+",
    "diagnostico": "Saludable"
  },
  {
    "id": 23,
    "nombre": "Estefania",
    "apellido": "Ceballos",
    "dni": "34567890W",
    "edad": 23,
    "direccion": "Calle Noche 456",
    "telefono": "634567890",
    "grupo Sanguineo": "B-",
    "diagnostico": "Saludable"
  },
  {
    "id": 24,
    "nombre": "Alberto",
    "apellido": "Salazar",
    "dni": "45678901X",
    "edad": 37,
    "direccion": "Calle Océano 987",
    "telefono": "645678901",
    "grupo Sanguineo": "AB-",
    "diagnostico": "Hipertensión"
  },
  {
    "id": 25,
    "nombre": "Veronica",
    "apellido": "Hurtado",
    "dni": "56789012Y",
    "edad": 41,
    "direccion": "Calle Aurora 321",
    "telefono": "656789012",
    "grupo Sanguineo": "O-",
    "diagnostico": "Saludable"
  }
]
